version: 2
before:
  hooks:
    - go mod tidy

builds:
  - id: mffprober
    main: ./main
    ldflags:
      - -s
      - -w 
      - -X main.version={{.Version}}
      - -X main.gitCommit={{.ShortCommit}}
      - -X main.binaryName={{.ProjectName}}
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64

universal_binaries:
  - id: mffprober
    replace: true

archives:
  - id: mffprober
    format_overrides:
      - goos: windows
        formats: zip
      - goos: darwin
        formats: zip
    files:
      - LICENSE
  
nfpms:
  - id: mffprober
    maintainer: "Marko Milivojevic <markom@gmail.com>"
    description: "Modern Forms Fan prober See: https://github.com/icemarkom/mffprober"
    bindir: /usr/local/bin
    formats:
      - apk
      - deb
      - rpm

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'

announce:
  skip: "true"
